[package]
name = "restaurant-files"
version = "0.1.0"
authors = ["Snorre lothar von Gohren Edwin <snorre.edwin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
